name: city_waste_management
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.0
  firebase_database: ^10.0.14
  cloud_firestore: ^4.4.4
  firebase_auth: ^4.2.10
  get: ^4.6.5
  lottie: ^2.2.0
  google_fonts: ^4.0.3
  flutter_spinkit: ^5.1.0
  glass: ^1.0.1+1
  sweet_nav_bar: ^1.0.5
  google_maps_flutter: ^2.2.5
  at_gauges: ^1.0.1
  flutter_launcher_icons_maker: ^0.10.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  macos: true
  windows: true
  web: true
  image_path: "assets/images/lanIcon.png"


  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true

  assets:
    - assets/images/


